# Generated by Django 5.0.7 on 2024-07-11 06:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imgrecog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='img',
        ),
        migrations.RemoveField(
            model_name='image',
            name='name',
        ),
        migrations.AddField(
            model_name='image',
            name='caption',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='image',
            name='image',
            field=models.ImageField(default=datetime.datetime(2024, 7, 11, 6, 41, 3, 74842, tzinfo=datetime.timezone.utc), upload_to='images'),
            preserve_default=False,
        ),
    ]
