# Generated by Django 5.0.7 on 2024-07-11 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imgrecog', '0002_remove_image_img_remove_image_name_image_caption_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='caption',
            field=models.CharField(max_length=200),
        ),
    ]
